### ISSUE TITLE
Upstream AppleALC changes?

### ISSUE THREAD

**Issue by herrnst** [adhocfra/HuaweiMatebookD14RyzenHackintosh#2]
Hello,

first, thanks for sharing your EFI (am currently working on an EFI for the same laptop aswell, although I replaced the RTL8822CE with an Intel AX210 M.2 adapter, works very well with AirportItlwm and the BT Firmware patchery on Ventura so far; will share everything aswell when done).

In your README.md, you state you have a modified variant of AppleALC (plus layout id 21) to get the laptop microphone working. I found out that with "vanilla" / upstream AppleALC, the mic doesn't really work, although it is listed in the audio devices.

Mind sharing what has been changed in AppleALC? Or even send the changes upstream as an additional layout id for ALC256?

Thanks!

**Comment by adhocfra** [comment]
Hi, I'm not the developer of this AppleALC version, so I don't really know what's the differences between it.

**Comment by herrnst** [comment]
Thanks for the quick feedback. Do you have any pointers where it originates from?

**Comment by adhocfra** [comment]
Unfortunately I really don't remember now🫠
You can always open the kext and see the differences!

Il mar 26 set 2023, 09:57 Daniel Scheller ***@***.***> ha
scritto:

**Comment by herrnst** [comment]
The issue is that all layout-things are "lost" somewhere inside the actual binary (ie. Contents/MacOS/AppleALC), so that'll get difficult propably. Anyway, I'll see what I can find out. Thank you very much!

**Comment by herrnst** [comment]
Update: The AppleALC seem to (unconfirmed, untested) originate from [this fork](https://github.com/qhuyduong/AppleALC/), at least the top commits describe changes related to the mic handling on AMD systems. I asked the user about upstreaming these changes.
